In [2]:
import torch

In [6]:
device = 'cuda'

In [11]:
x = torch.tensor([2,4],device = 'cuda')

In [12]:
print(x.dtype)

torch.int64


In [13]:
x.device

device(type='cuda', index=0)

In [14]:
x.requires_grad

False

In [15]:
z = torch.eye(5,5)

In [16]:
z

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
ar = torch.arange(start = 2, end =10, step =2)

In [18]:
ar

tensor([2, 4, 6, 8])

In [19]:
en = torch.empty(size = (3,3))

In [20]:
en

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
y = torch.tensor([4,6])

In [4]:
print(x*y)

tensor([ 8, 24])


In [5]:
l = torch.zeros([2,4])

In [6]:
l

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
l.shape

torch.Size([2, 4])

In [15]:
m = torch.rand([2,6])

In [16]:
m

tensor([[0.4757, 0.8728, 0.2536, 0.9736, 0.8235, 0.9795],
        [0.5896, 0.5520, 0.2806, 0.5300, 0.6274, 0.8613]])

In [17]:
n = m.view(1,12)

In [18]:
n

tensor([[0.4757, 0.8728, 0.2536, 0.9736, 0.8235, 0.9795, 0.5896, 0.5520, 0.2806,
         0.5300, 0.6274, 0.8613]])

In [26]:
tensor = torch.tensor([4,6,235,24,65,1,4,0,7,0,70])

In [27]:
tensor

tensor([  4,   6, 235,  24,  65,   1,   4,   0,   7,   0,  70])

In [28]:
print(tensor.bool())

tensor([ True,  True,  True,  True,  True,  True,  True, False,  True, False,
         True])


In [29]:
tensor.short()

tensor([  4,   6, 235,  24,  65,   1,   4,   0,   7,   0,  70],
       dtype=torch.int16)

In [30]:
tensor.long()

tensor([  4,   6, 235,  24,  65,   1,   4,   0,   7,   0,  70])

In [31]:
tensor.half()

tensor([  4.,   6., 235.,  24.,  65.,   1.,   4.,   0.,   7.,   0.,  70.],
       dtype=torch.float16)

In [32]:
tensor.float()

tensor([  4.,   6., 235.,  24.,  65.,   1.,   4.,   0.,   7.,   0.,  70.])

In [33]:
import numpy as np

In [43]:
np_array = np.array([2,34,5.6,6,7])

In [44]:
tensor = torch.from_numpy(np_array)

In [45]:
tensor

tensor([ 2.0000, 34.0000,  5.6000,  6.0000,  7.0000], dtype=torch.float64)

In [46]:
np_array_back = tensor.numpy()

In [47]:
np_array_back

array([ 2. , 34. ,  5.6,  6. ,  7. ])

In [48]:
sum_tensor = torch.sum(tensor,dim = 0)

In [49]:
sum_tensor

tensor(54.6000, dtype=torch.float64)

In [41]:
tensor_abs = torch.abs(tensor)

In [50]:
tensor_abs

tensor([ 2, 34,  5,  6,  7], dtype=torch.int32)

In [55]:
z = torch.argmax(tensor,dim = 0)

In [56]:
z

tensor(1)

In [57]:
sorted_t = torch.sort(tensor,dim = 0, descending = False)

In [58]:
sorted_t

torch.return_types.sort(
values=tensor([ 2.0000,  5.6000,  6.0000,  7.0000, 34.0000], dtype=torch.float64),
indices=tensor([0, 2, 3, 4, 1]))

In [59]:
g = torch.clamp(tensor,min = 0)

In [60]:
g

tensor([ 2.0000, 34.0000,  5.6000,  6.0000,  7.0000], dtype=torch.float64)

In [61]:
x = torch.tensor([1,0,1,1,1,1,0,5,4])

In [62]:
z = torch.any(x)

In [63]:
z

tensor(True)

In [3]:
x = torch.rand((10,25))

In [12]:
x[:,0]

tensor([0.9230, 0.5616, 0.8371, 0.4745, 0.6014, 0.5618, 0.7103, 0.6095, 0.1391,
        0.7735])

In [13]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [14]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)

In [15]:
x1

tensor([[0.7506, 0.5297, 0.6342, 0.4262, 0.7265],
        [0.3615, 0.9308, 0.3904, 0.0228, 0.8900]])

In [16]:
x2

tensor([[0.8658, 0.3620, 0.7494, 0.5488, 0.4915],
        [0.9470, 0.3032, 0.8466, 0.4557, 0.0188]])

In [17]:
x3 = torch.cat((x1,x2),dim =0)

In [18]:
x3

tensor([[0.7506, 0.5297, 0.6342, 0.4262, 0.7265],
        [0.3615, 0.9308, 0.3904, 0.0228, 0.8900],
        [0.8658, 0.3620, 0.7494, 0.5488, 0.4915],
        [0.9470, 0.3032, 0.8466, 0.4557, 0.0188]])

In [19]:
x4 = torch.cat((x1,x2),dim =1)

In [20]:
x4

tensor([[0.7506, 0.5297, 0.6342, 0.4262, 0.7265, 0.8658, 0.3620, 0.7494, 0.5488,
         0.4915],
        [0.3615, 0.9308, 0.3904, 0.0228, 0.8900, 0.9470, 0.3032, 0.8466, 0.4557,
         0.0188]])

In [21]:
z1 = x1.view(-1)

In [23]:
z1.shape

torch.Size([10])

In [29]:
x = torch.rand((2, 2, 5))

In [30]:
x

tensor([[[0.0135, 0.8157, 0.1310, 0.7628, 0.1696],
         [0.3805, 0.9563, 0.6345, 0.2148, 0.6032]],

        [[0.2868, 0.6888, 0.4803, 0.2612, 0.0875],
         [0.2924, 0.5071, 0.4027, 0.4237, 0.0910]]])

In [31]:
z = x.permute(0, 2, 1)

In [32]:
z.shape

torch.Size([2, 5, 2])

In [33]:
z

tensor([[[0.0135, 0.3805],
         [0.8157, 0.9563],
         [0.1310, 0.6345],
         [0.7628, 0.2148],
         [0.1696, 0.6032]],

        [[0.2868, 0.2924],
         [0.6888, 0.5071],
         [0.4803, 0.4027],
         [0.2612, 0.4237],
         [0.0875, 0.0910]]])

In [34]:
z2 = torch.chunk(x, chunks=2, dim=1)

In [35]:
z2

(tensor([[[0.0135, 0.8157, 0.1310, 0.7628, 0.1696]],
 
         [[0.2868, 0.6888, 0.4803, 0.2612, 0.0875]]]),
 tensor([[[0.3805, 0.9563, 0.6345, 0.2148, 0.6032]],
 
         [[0.2924, 0.5071, 0.4027, 0.4237, 0.0910]]]))

In [37]:
z2[0].shape

torch.Size([2, 1, 5])

In [38]:
z2[1].shape

torch.Size([2, 1, 5])

In [46]:
x = torch.arange(10)

In [42]:
x.shape

torch.Size([10])

In [40]:
z1 = x.unsqueeze(0)

In [41]:
z1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
z1.shape

torch.Size([1, 10])

In [47]:
z2 = x.unsqueeze(1)

In [48]:
z2

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [49]:
z2.shape

torch.Size([10, 1])

In [62]:
x = torch.arange(10).unsqueeze(0)

In [63]:
x2 = x.unsqueeze(1)

In [64]:
x2.shape

torch.Size([1, 1, 10])

In [65]:
x2

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [66]:
z = x2.squeeze(1)

In [67]:
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])